baseURL = "http://example.org/"
languageCode = "en-us"
title = "StackBack"
theme = "hugo-material-docs"
metadataformat = "yaml"
#canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	version = "1.0.2"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Syntax highlighting theme
	highlight_css  = ""

	# Custom assets
  custom_css = ["material_table.css", "tablesort.css"]
	custom_js = ["tablesort.min.js", "tablesort.date.min.js", "tablesort.number.min.js"]

[params.palette]
  primary = "red"
  accent  = "teal"

  [params.font]
    text = "Ubuntu"
    code = "Ubuntu Mono"

[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Accounts"
	url    = "accounts/"
	weight = 20

[[menu.main]]
	name   = "Projects"
	url    = "projects/"
	weight = 20

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
